require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.comment"

vim.g["neodark#background"] = "#1F1F1F"
vim.cmd "colorscheme neodark"
