require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.impatient"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.comment"
require "user.bufferline"
require "user.lualine"
-- require "user.whichkey"

vim.g["neodark#background"] = "#1F1F1F"
vim.cmd "colorscheme neodark"
