require "user.options"
require "user.autocommands"
require "user.plugins"
require "user.keymaps"
require "user.impatient"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.comment"
require "user.bufferline"
require "user.toggleterm"
require "user.lualine"
require "user.whichkey"
require "user.dap"

vim.g["neodark#background"] = "#121212"
vim.cmd "colorscheme neodark"
