-- local status_ok, vimtex = pcall(require, "vimtex")
-- if not status_ok then
--   return
-- end
-- if vim.bo.filetype == "tex" then
--
--     vim.g.maplocalleader = " "
--     vim.g.vimtex_view_method = "zathura"
--     vim.o.conceallevel = 1 
--     vim.o.spell = true
--
-- end
